import streamlit as st

st.sidebar.success("Select above page.")

st.title(":green[Parkinson's Disease]")
st.subheader(":blue[1. What is Parkinson's Disease ?]")
st.write("Parkinson's disease is a progressive disorder that affects the nervous system and the parts of the body controlled by the nerves. Symptoms start slowly. The first symptom may be a barely noticeable tremor in just one hand. Tremors are common, but the disorder may also cause stiffness or slowing of movement.")
st.write("In the early stages of Parkinson's disease, your face may show little or no expression. Your arms may not swing when you walk. Your speech may become soft or slurred. Parkinson's disease symptoms worsen as your condition progresses over time.")
st.write("Although Parkinson's disease can't be cured, medications might significantly improve your symptoms. Occasionally, your health care provider may suggest surgery to regulate certain regions of your brain and improve your symptoms.")
st.subheader(":blue[2. Symptoms of Parkinson's Disease ?]")
st.write("Parkinson's disease symptoms can be different for everyone. Early symptoms may be mild and go unnoticed. Symptoms often begin on one side of the body and usually remain worse on that side, even after symptoms begin to affect the limbs on both sides.")
st.write("Parkinson's symptoms may include:")
st.subheader("Tremor :")
st.write("Rhythmic shaking, called tremor, usually begins in a limb, often your hand or fingers. You may rub your thumb and forefinger back and forth. This is known as a pill-rolling tremor. Your hand may tremble when it's at rest. The shaking may decrease when you are performing tasks.")
st.subheader("Slowed movement, known as bradykinesia :")
st.write("Over time, Parkinson's disease may slow your movement, making simple tasks difficult and time-consuming. Your steps may become shorter when you walk. It may be difficult to get out of a chair. You may drag or shuffle your feet as you try to walk.")
st.subheader("Rigid muscles :")
st.write("Muscle stiffness may occur in any part of your body. The stiff muscles can be painful and limit your range of motion.")
st.subheader("Impaired posture and balance :")
st.write("Your posture may become stooped. Or you may fall or have balance problems as a result of Parkinson's disease.")
st.subheader("Loss of automatic movements :")
st.write("You may have a decreased ability to perform unconscious movements, including blinking, smiling or swinging your arms when you walk.")
st.subheader("Speech changes :")
st.write("You may speak softly or quickly, slur, or hesitate before talking. Your speech may be more of a monotone rather than have the usual speech patterns.")
st.subheader("Writing changes :")
st.write("It may become hard to write, and your writing may appear small.")
st.subheader(":blue[3. Causes of Parkinson's Disease ?]")
st.write("In Parkinson's disease, certain nerve cells called neurons in the brain gradually break down or die. Many of the symptoms of Parkinson's are due to a loss of neurons that produce a chemical messenger in your brain called dopamine. When dopamine levels decrease, it causes irregular brain activity, leading to problems with movement and other symptoms of Parkinson's disease.")
st.write("The cause of Parkinson's disease is unknown, but several factors appear to play a role, including:")
st.subheader("Genes :")
st.write("Rhythmic shaking, called tremor, usually begins in a limb, often your hand or fingers. You may rub your thumb and forefinger back and forth. This is known as a pill-rolling tremor. Your hand may tremble when it's at rest. The shaking may decrease when you are performing tasks.")
st.subheader("Environmental triggers :")
st.write("Rhythmic shaking, called tremor, usually begins in a limb, often your hand or fingers. You may rub your thumb and forefinger back and forth. This is known as a pill-rolling tremor. Your hand may tremble when it's at rest. The shaking may decrease when you are performing tasks.")
st.write("Researchers also have noted that many changes occur in the brains of people with Parkinson's disease, although it's not clear why these changes occur. These changes include:")
st.subheader("The presence of Lewy bodies :")
st.write("Rhythmic shaking, called tremor, usually begins in a limb, often your hand or fingers. You may rub your thumb and forefinger back and forth. This is known as a pill-rolling tremor. Your hand may tremble when it's at rest. The shaking may decrease when you are performing tasks.")
st.subheader("Alpha-synuclein found within Lewy bodies :")
st.write("Rhythmic shaking, called tremor, usually begins in a limb, often your hand or fingers. You may rub your thumb and forefinger back and forth. This is known as a pill-rolling tremor. Your hand may tremble when it's at rest. The shaking may decrease when you are performing tasks.")
st.subheader(":blue[4. Risk factors of Parkinson's Disease ?]")
st.write("Risk factors for Parkinson's disease include:")
st.subheader("Age :")
st.write("Young adults rarely experience Parkinson's disease. It ordinarily begins in middle or late life, and the risk increases with age. People usually develop the disease around age 60 or older. If a young person does have Parkinson's disease, genetic counseling might be helpful in making family planning decisions. Work, social situations and medicine side effects are also different from those of an older person with Parkinson's disease and require special considerations.")
st.subheader("Heredity :")
st.write("Having a close relative with Parkinson's disease increases the chances that you'll develop the disease. However, your risks are still small unless you have many relatives in your family with Parkinson's disease.")
st.subheader("Sex :")
st.write("Men are more likely to develop Parkinson's disease than are women.")
st.subheader("Exposure to toxins :")
st.write("Ongoing exposure to herbicides and pesticides may slightly increase your risk of Parkinson's disease.")
st.subheader(":blue[5. Prevention of Parkinson's Disease ?]")
st.write("Because the cause of Parkinson's is unknown, there are no proven ways to prevent the disease.")
st.write("Some research has shown that regular aerobic exercise might reduce the risk of Parkinson's disease.")
st.write("Some other research has shown that people who consume caffeine — which is found in coffee, tea and cola — get Parkinson's disease less often than those who don't drink it. Green tea also is related to a reduced risk of developing Parkinson's disease. However, it is still not known whether caffeine protects against getting Parkinson's or is related in some other way. Currently there is not enough evidence to suggest that drinking caffeinated beverages protects against Parkinson's.")

st.title(":green[How to Use Prediction System]")
st.subheader("Just Enter all parameters in Prediction Page and click on :blue[Prediction Test Result.]")